[book]
title = "py-onramp"
description = "An onramp to the modern data and scientific Python workflow."
src = "docs"

[build]
build-dir = "site"

[output.html]
git-repository-url = "https://github.com/Tufts-University/py-onramp"
edit-url-template = "https://github.com/Tufts-University/py-onramp/edit/master/{path}"
mathjax-support = true
